version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: sign
      POSTGRES_PASSWORD: S3cureP@ssw0rd!
      POSTGRES_DB: sign-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
