# Generated by Django 5.1 on 2024-12-14 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_openid_document_open_id_alter_document_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signer',
            name='token',
        ),
    ]
