# Generated by Django 5.1 on 2024-12-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_signer_token_alter_document_company_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='signer',
            old_name='document_id',
            new_name='document',
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('SIGNED', 'signed'), ('PENDING', 'pending'), ('NEW', 'new'), ('LINK_OPENED', 'link_opened')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='signer',
            name='status',
            field=models.CharField(choices=[('SIGNED', 'signed'), ('PENDING', 'pending'), ('NEW', 'new'), ('LINK_OPENED', 'link_opened')], default='NEW', max_length=15),
        ),
    ]
