# Generated by Django 5.1 on 2024-12-15 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_company_id_document_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('SIGNED', 'signed'), ('REFUSED', 'refused'), ('PENDING', 'pending'), ('NEW', 'new'), ('LINK_OPENED', 'link_opened')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='signer',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='api.document'),
        ),
        migrations.AlterField(
            model_name='signer',
            name='status',
            field=models.CharField(choices=[('SIGNED', 'signed'), ('REFUSED', 'refused'), ('PENDING', 'pending'), ('NEW', 'new'), ('LINK_OPENED', 'link_opened')], default='NEW', max_length=15),
        ),
    ]
