# Generated by Django 5.1 on 2024-12-16 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_document_status_alter_signer_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='api.company'),
        ),
    ]
