class ErrosMessageEnum():
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
    COMPANY_NOT_FOUND = 'COMPANY_NOT_FOUND'
    DOCUMENT_NOT_FOUND = 'DOCUMENT_NOT_FOUND'
    SIGNER_NOT_FOUND = 'SIGNER_NOT_FOUND'
    COMPANY_NOT_CREATED = 'COMPANY_NOT_CREATED'
    DOCUMENT_NOT_CREATED = 'DOCUMENT_NOT_CREATED'
